package wsc_application;
import javax.swing.JFrame;

public class WilliamsSpecialtyGUI extends javax.swing.JPanel {

    /**
     * Creates new form WilliamsSpecialtyGUI
     */
    public WilliamsSpecialtyGUI() {
        initComponents();
    }
    
    protected static void createAndShowGUI() {
        JFrame frame = new JFrame(SrProject.appTitle);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        frame.add(new WilliamsSpecialtyGUI());
        frame.pack();
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        OrderPayTypeBG = new javax.swing.ButtonGroup();
        OrderTypeBG = new javax.swing.ButtonGroup();
        OrderEngMediaBG = new javax.swing.ButtonGroup();
        OrderStatusBG = new javax.swing.ButtonGroup();
        OrderMediaStatusBG = new javax.swing.ButtonGroup();
        WSCInterface = new javax.swing.JTabbedPane();
        MediaInventoryPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        QAPanel = new javax.swing.JPanel();
        OrderInfoPanel = new javax.swing.JPanel();
        OrderNumberLbl = new javax.swing.JLabel();
        OrderDeliverPayRB = new javax.swing.JRadioButton();
        OrderAccountPayRB = new javax.swing.JRadioButton();
        OrderDepositLbl = new javax.swing.JLabel();
        OrderDepositText = new javax.swing.JTextField();
        OrderNumberText = new javax.swing.JTextField();
        OrderTypePrintRB = new javax.swing.JRadioButton();
        OrderTypeEngrRB = new javax.swing.JRadioButton();
        OrderTypeTrophyRB = new javax.swing.JRadioButton();
        OrderTypePlaqueRB = new javax.swing.JRadioButton();
        OrderContentLbl = new javax.swing.JLabel();
        OrderContentText = new javax.swing.JTextField();
        OrderMediaCatNumLbl = new javax.swing.JLabel();
        OrderMediaCatNumText = new javax.swing.JTextField();
        OrderDetailsText = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        OrderDetailsLbl = new javax.swing.JLabel();
        OrderStatusRBLbl = new javax.swing.JLabel();
        OrderVerifiedRB = new javax.swing.JRadioButton();
        OrderCreatedRB = new javax.swing.JRadioButton();
        OrderMediaHoldRB = new javax.swing.JRadioButton();
        OrderWorkingRB = new javax.swing.JRadioButton();
        OrderPECompleteRB = new javax.swing.JRadioButton();
        OrderQAPassedRB = new javax.swing.JRadioButton();
        OrderQAFailedRB = new javax.swing.JRadioButton();
        OrderHoldForPayRB = new javax.swing.JRadioButton();
        OrderClosedRB = new javax.swing.JRadioButton();
        OrderMediaStatusRBLbl = new javax.swing.JLabel();
        OrderMNotVerified = new javax.swing.JRadioButton();
        OrderMNotRequested = new javax.swing.JRadioButton();
        OrderMSoldRB = new javax.swing.JRadioButton();
        OrderMOnOrderRB = new javax.swing.JRadioButton();
        OrderMEnRouteRB = new javax.swing.JRadioButton();
        OrderMDeliveredRB = new javax.swing.JRadioButton();
        OrderJobTypeLbl = new javax.swing.JLabel();
        OrderCustNumberLbl = new javax.swing.JLabel();
        OrderCustomerNumberText = new javax.swing.JTextField();
        OrderTrackingPanel = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        LoginPanel = new javax.swing.JPanel();
        LoginSubmitButton = new javax.swing.JButton();
        LoginEMPIDField = new javax.swing.JTextField();
        LoginEMPIDLabel = new javax.swing.JLabel();
        LoginPASSLabel = new javax.swing.JLabel();
        LoginPasswordFieldText = new javax.swing.JPasswordField();
        CustomerInfoPanel = new javax.swing.JPanel();
        CustBillFNameText = new javax.swing.JTextField();
        CustBillLNameText = new javax.swing.JTextField();
        CustBillOrgText = new javax.swing.JTextField();
        CustBillStreet1Text = new javax.swing.JTextField();
        CustBillStreet2Text = new javax.swing.JTextField();
        CustBillFNameLbl = new javax.swing.JLabel();
        CustBillLNameLbl = new javax.swing.JLabel();
        CustBillOrgLbl = new javax.swing.JLabel();
        CustBillStreet1Lbl = new javax.swing.JLabel();
        CustBillStreet2Lbl = new javax.swing.JLabel();
        CustBillCityText = new javax.swing.JTextField();
        CustBillZipText = new javax.swing.JTextField();
        CustBillCityLbl = new javax.swing.JLabel();
        CustBillZipLbl = new javax.swing.JLabel();
        BillingLbl = new javax.swing.JLabel();
        ShippLbl = new javax.swing.JLabel();
        SameAsBillCheckBox = new javax.swing.JCheckBox();
        CustShipFNameLbl = new javax.swing.JLabel();
        CustShipZipLbl = new javax.swing.JLabel();
        CustShipZipText = new javax.swing.JTextField();
        CustShipCityText = new javax.swing.JTextField();
        CustShipStreet2Text = new javax.swing.JTextField();
        CustShipStreet1Text = new javax.swing.JTextField();
        CustShipOrgText = new javax.swing.JTextField();
        CustShipLNameText = new javax.swing.JTextField();
        CustShipFNameText = new javax.swing.JTextField();
        CustShipLNameLbl = new javax.swing.JLabel();
        CustShipOrgLbl = new javax.swing.JLabel();
        CustShipStreet1Lbl = new javax.swing.JLabel();
        CustShipStreet2Lbl = new javax.swing.JLabel();
        CustShipCityLbl = new javax.swing.JLabel();
        CustFindButton = new javax.swing.JButton();
        CustCreateButton = new javax.swing.JButton();
        CustOrderListBox = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        CustOrderListBoxLbl = new javax.swing.JLabel();
        CustCreateButton1 = new javax.swing.JButton();
        CustCommBox = new javax.swing.JScrollPane();
        CustCommentText = new javax.swing.JTextArea();
        CustCommentLbl = new javax.swing.JLabel();
        ActiveOrderLbl = new javax.swing.JLabel();
        CustNumberLbl = new javax.swing.JLabel();
        CustNumberText = new javax.swing.JTextField();
        CustShipStateComB = new javax.swing.JComboBox();
        CustShipStateCB = new javax.swing.JComboBox();

        jLabel1.setText("Item Number");

        jLabel2.setText("Manufacturer");

        jLabel3.setText("jLabel3");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout MediaInventoryPanelLayout = new javax.swing.GroupLayout(MediaInventoryPanel);
        MediaInventoryPanel.setLayout(MediaInventoryPanelLayout);
        MediaInventoryPanelLayout.setHorizontalGroup(
            MediaInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MediaInventoryPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(MediaInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MediaInventoryPanelLayout.createSequentialGroup()
                        .addGroup(MediaInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MediaInventoryPanelLayout.createSequentialGroup()
                        .addGroup(MediaInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MediaInventoryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(877, 877, 877))
        );
        MediaInventoryPanelLayout.setVerticalGroup(
            MediaInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MediaInventoryPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(MediaInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MediaInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(446, Short.MAX_VALUE))
        );

        WSCInterface.addTab("Media Inventory", MediaInventoryPanel);

        javax.swing.GroupLayout QAPanelLayout = new javax.swing.GroupLayout(QAPanel);
        QAPanel.setLayout(QAPanelLayout);
        QAPanelLayout.setHorizontalGroup(
            QAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1254, Short.MAX_VALUE)
        );
        QAPanelLayout.setVerticalGroup(
            QAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        WSCInterface.addTab("Quality Assurance", QAPanel);

        OrderNumberLbl.setText("Order Number:");

        OrderPayTypeBG.add(OrderDeliverPayRB);
        OrderDeliverPayRB.setText("Payment on Delivery");

        OrderPayTypeBG.add(OrderAccountPayRB);
        OrderAccountPayRB.setText("Payment on Account");

        OrderDepositLbl.setText("Deposit Amount");

        OrderDepositText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderDepositTextActionPerformed(evt);
            }
        });

        OrderTypeBG.add(OrderTypePrintRB);
        OrderTypePrintRB.setText("Printing");

        OrderTypeBG.add(OrderTypeEngrRB);
        OrderTypeEngrRB.setText("Engraving");

        OrderEngMediaBG.add(OrderTypeTrophyRB);
        OrderTypeTrophyRB.setText("Trophy");

        OrderEngMediaBG.add(OrderTypePlaqueRB);
        OrderTypePlaqueRB.setText("Plaque");

        OrderContentLbl.setText("Printing/Engraving Content:");

        OrderMediaCatNumLbl.setText("Media Catalog Number:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        OrderDetailsText.setViewportView(jTextArea1);

        OrderDetailsLbl.setText("Order Details:");

        OrderStatusRBLbl.setText("Order Status:");

        OrderStatusBG.add(OrderVerifiedRB);
        OrderVerifiedRB.setText("Verified");

        OrderStatusBG.add(OrderCreatedRB);
        OrderCreatedRB.setText("Created");
        OrderCreatedRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderCreatedRBActionPerformed(evt);
            }
        });

        OrderStatusBG.add(OrderMediaHoldRB);
        OrderMediaHoldRB.setText("Product Hold");

        OrderStatusBG.add(OrderWorkingRB);
        OrderWorkingRB.setText("Working");

        OrderStatusBG.add(OrderPECompleteRB);
        OrderPECompleteRB.setText("P/E Completed");
        OrderPECompleteRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderPECompleteRBActionPerformed(evt);
            }
        });

        OrderStatusBG.add(OrderQAPassedRB);
        OrderQAPassedRB.setText("Q/A Passed");

        OrderStatusBG.add(OrderQAFailedRB);
        OrderQAFailedRB.setText("Q/A Failed");

        OrderStatusBG.add(OrderHoldForPayRB);
        OrderHoldForPayRB.setText("Hold for Payment");

        OrderStatusBG.add(OrderClosedRB);
        OrderClosedRB.setText("Closed");

        OrderMediaStatusRBLbl.setText("Media Status:");

        OrderMediaStatusBG.add(OrderMNotVerified);
        OrderMNotVerified.setText("Order Not Verified");

        OrderMediaStatusBG.add(OrderMNotRequested);
        OrderMNotRequested.setText("Not Requested");

        OrderMediaStatusBG.add(OrderMSoldRB);
        OrderMSoldRB.setText("Requested/Sold");

        OrderMediaStatusBG.add(OrderMOnOrderRB);
        OrderMOnOrderRB.setText("Requested/On Order");

        OrderMediaStatusBG.add(OrderMEnRouteRB);
        OrderMEnRouteRB.setText("En Route");

        OrderMediaStatusBG.add(OrderMDeliveredRB);
        OrderMDeliveredRB.setText("Delivered");

        OrderJobTypeLbl.setText("Job Type:");

        OrderCustNumberLbl.setText("Customer Number:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, CustNumberText, org.jdesktop.beansbinding.ELProperty.create("${text_ON_ACTION_OR_FOCUS_LOST}"), OrderCustomerNumberText, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        OrderCustomerNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderCustomerNumberTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrderInfoPanelLayout = new javax.swing.GroupLayout(OrderInfoPanel);
        OrderInfoPanel.setLayout(OrderInfoPanelLayout);
        OrderInfoPanelLayout.setHorizontalGroup(
            OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                        .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                                .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OrderMediaCatNumLbl)
                                    .addComponent(OrderNumberLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(OrderNumberText, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(OrderMediaCatNumText, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(OrderCustomerNumberText)))
                            .addComponent(OrderTypeEngrRB)
                            .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OrderTypePlaqueRB)
                                    .addComponent(OrderTypeTrophyRB)))
                            .addComponent(OrderTypePrintRB)
                            .addComponent(OrderJobTypeLbl)
                            .addComponent(OrderCustNumberLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrderContentText, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OrderContentLbl))
                        .addGap(56, 56, 56)
                        .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrderQAFailedRB)
                            .addComponent(OrderHoldForPayRB)
                            .addComponent(OrderClosedRB)
                            .addComponent(OrderCreatedRB)
                            .addComponent(OrderStatusRBLbl)
                            .addComponent(OrderVerifiedRB)
                            .addComponent(OrderMediaHoldRB)
                            .addComponent(OrderWorkingRB)
                            .addComponent(OrderPECompleteRB)
                            .addComponent(OrderQAPassedRB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrderMEnRouteRB)
                            .addComponent(OrderMOnOrderRB)
                            .addComponent(OrderMSoldRB)
                            .addComponent(OrderMediaStatusRBLbl)
                            .addComponent(OrderMNotVerified)
                            .addComponent(OrderMNotRequested)
                            .addComponent(OrderMDeliveredRB))
                        .addGap(30, 30, 30))
                    .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                        .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(OrderDepositLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OrderDepositText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(OrderAccountPayRB)
                            .addComponent(OrderDeliverPayRB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OrderDetailsLbl)
                    .addComponent(OrderDetailsText, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
        OrderInfoPanelLayout.setVerticalGroup(
            OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                        .addComponent(OrderDetailsLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OrderDetailsText, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                        .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                                .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(OrderCustNumberLbl)
                                    .addComponent(OrderCustomerNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(OrderNumberLbl)
                                    .addComponent(OrderNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(OrderMediaCatNumLbl)
                                    .addComponent(OrderMediaCatNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addComponent(OrderJobTypeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderTypePrintRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderTypeEngrRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderTypeTrophyRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderTypePlaqueRB))
                            .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                                .addComponent(OrderMediaStatusRBLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderMNotVerified)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderMNotRequested)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderMSoldRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderMOnOrderRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderMEnRouteRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderMDeliveredRB))
                            .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                                .addComponent(OrderStatusRBLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderCreatedRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderVerifiedRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderMediaHoldRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderWorkingRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderPECompleteRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderQAPassedRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderQAFailedRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderHoldForPayRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderClosedRB))
                            .addGroup(OrderInfoPanelLayout.createSequentialGroup()
                                .addComponent(OrderContentLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OrderContentText)))
                        .addGap(32, 32, 32)
                        .addComponent(OrderAccountPayRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OrderDeliverPayRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OrderInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OrderDepositLbl)
                            .addComponent(OrderDepositText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        WSCInterface.addTab("Order Info", OrderInfoPanel);

        jCheckBox1.setText("Customer Number");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Employee Number");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Order Number");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Search:");

        jLabel5.setText("Search By:");

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList2);

        javax.swing.GroupLayout OrderTrackingPanelLayout = new javax.swing.GroupLayout(OrderTrackingPanel);
        OrderTrackingPanel.setLayout(OrderTrackingPanelLayout);
        OrderTrackingPanelLayout.setHorizontalGroup(
            OrderTrackingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderTrackingPanelLayout.createSequentialGroup()
                .addGroup(OrderTrackingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderTrackingPanelLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addGroup(OrderTrackingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OrderTrackingPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(OrderTrackingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox3)))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OrderTrackingPanelLayout.createSequentialGroup()
                        .addContainerGap(241, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(286, 286, 286))
        );
        OrderTrackingPanelLayout.setVerticalGroup(
            OrderTrackingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderTrackingPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(OrderTrackingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(OrderTrackingPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(OrderTrackingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        WSCInterface.addTab("Order Tracking", OrderTrackingPanel);

        LoginSubmitButton.setText("Login");
        LoginSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginSubmitButtonActionPerformed(evt);
            }
        });

        LoginEMPIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginEMPIDFieldActionPerformed(evt);
            }
        });

        LoginEMPIDLabel.setText("Employee ID");

        LoginPASSLabel.setText("Password");

        LoginPasswordFieldText.setText("jPasswordField1");
        LoginPasswordFieldText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPasswordFieldTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginEMPIDLabel)
                            .addComponent(LoginPASSLabel))
                        .addGap(18, 18, 18)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LoginEMPIDField)
                            .addComponent(LoginPasswordFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(LoginSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(694, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginEMPIDLabel)
                    .addComponent(LoginEMPIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginPASSLabel)
                    .addComponent(LoginPasswordFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(LoginSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        WSCInterface.addTab("Login", LoginPanel);

        CustBillLNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustBillLNameTextActionPerformed(evt);
            }
        });

        CustBillStreet2Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustBillStreet2TextActionPerformed(evt);
            }
        });

        CustBillFNameLbl.setText("First Name");

        CustBillLNameLbl.setText("Last Name");

        CustBillOrgLbl.setText("Organization");

        CustBillStreet1Lbl.setText("Street Address Line 1");

        CustBillStreet2Lbl.setText("Street Address Line 2");

        CustBillZipText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustBillZipTextActionPerformed(evt);
            }
        });

        CustBillCityLbl.setText("City");

        CustBillZipLbl.setText("Zip");

        BillingLbl.setText("Billing:");

        ShippLbl.setText("Shipping:");

        SameAsBillCheckBox.setText("Same as Billing");
        SameAsBillCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SameAsBillCheckBoxActionPerformed(evt);
            }
        });

        CustShipFNameLbl.setText("First Name");

        CustShipZipLbl.setText("Zip");

        CustShipZipText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustShipZipTextActionPerformed(evt);
            }
        });

        CustShipStreet2Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustShipStreet2TextActionPerformed(evt);
            }
        });

        CustShipStreet1Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustShipStreet1TextActionPerformed(evt);
            }
        });

        CustShipLNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustShipLNameTextActionPerformed(evt);
            }
        });

        CustShipLNameLbl.setText("Last Name");

        CustShipOrgLbl.setText("Organization");

        CustShipStreet1Lbl.setText("Street Address Line 1");

        CustShipStreet2Lbl.setText("Street Address Line 2");

        CustShipCityLbl.setText("City");

        CustFindButton.setText("Find");
        CustFindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustFindButtonActionPerformed(evt);
            }
        });

        CustCreateButton.setText("Create/Update");
        CustCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustCreateButtonActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        CustOrderListBox.setViewportView(jList1);

        CustOrderListBoxLbl.setText("Order(s):");

        CustCreateButton1.setText("Clear Fields");
        CustCreateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustCreateButton1ActionPerformed(evt);
            }
        });

        CustCommentText.setColumns(20);
        CustCommentText.setRows(5);
        CustCommBox.setViewportView(CustCommentText);

        CustCommentLbl.setText("Notes/Comments:");

        ActiveOrderLbl.setForeground(new java.awt.Color(255, 0, 0));
        ActiveOrderLbl.setText("*Active orders in red");

        CustNumberLbl.setText("Customer Number");

        CustShipStateComB.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"", "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA",
            "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
            "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY" }));
CustShipStateComB.setPreferredSize(new java.awt.Dimension(35, 20));
CustShipStateComB.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        CustShipStateComBActionPerformed(evt);
    }
    });

    CustShipStateCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"", "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA",
        "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH",
        "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY" }));
CustShipStateCB.setPreferredSize(new java.awt.Dimension(35, 20));
CustShipStateCB.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
    CustShipStateCBActionPerformed(evt);
    }
    });

    javax.swing.GroupLayout CustomerInfoPanelLayout = new javax.swing.GroupLayout(CustomerInfoPanel);
    CustomerInfoPanel.setLayout(CustomerInfoPanelLayout);
    CustomerInfoPanelLayout.setHorizontalGroup(
        CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
            .addGap(281, 281, 281)
            .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(CustCommBox)
                .addComponent(CustCommentLbl)
                .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                    .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                                .addComponent(CustBillStreet2Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustBillStreet2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                                .addComponent(CustBillStreet1Lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustBillStreet1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                                .addComponent(CustFindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustCreateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustCreateButton1))
                            .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                                .addComponent(CustNumberLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CustNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))
                            .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                                    .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CustBillLNameLbl)
                                        .addComponent(CustBillFNameLbl))
                                    .addGap(56, 56, 56)
                                    .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CustBillFNameText)
                                        .addComponent(CustBillLNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                                    .addComponent(CustBillOrgLbl)
                                    .addGap(46, 46, 46)
                                    .addComponent(CustBillOrgText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(BillingLbl, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addComponent(CustShipStateComB, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustomerInfoPanelLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(CustBillZipLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CustBillZipText))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CustomerInfoPanelLayout.createSequentialGroup()
                                .addComponent(CustBillCityLbl)
                                .addGap(88, 88, 88)
                                .addComponent(CustBillCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(31, 31, 31)
                    .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                            .addComponent(ShippLbl)
                            .addGap(29, 29, 29)
                            .addComponent(SameAsBillCheckBox))
                        .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                            .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                                    .addComponent(CustShipStateCB, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(CustShipZipLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CustShipZipText))
                                .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                                    .addComponent(CustShipCityLbl)
                                    .addGap(88, 88, 88)
                                    .addComponent(CustShipCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                                    .addComponent(CustShipStreet2Lbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CustShipStreet2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                                    .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CustShipStreet1Lbl)
                                        .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(CustShipLNameLbl)
                                                .addComponent(CustShipOrgLbl)))
                                        .addComponent(CustShipFNameLbl))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CustShipFNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CustShipOrgText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CustShipStreet1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CustShipLNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(30, 30, 30)
                            .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CustOrderListBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(ActiveOrderLbl))
                                .addComponent(CustOrderListBoxLbl))))))
            .addContainerGap(308, Short.MAX_VALUE))
    );
    CustomerInfoPanelLayout.setVerticalGroup(
        CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
            .addGap(92, 92, 92)
            .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(CustNumberLbl)
                .addComponent(CustNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(BillingLbl)
                .addComponent(ShippLbl)
                .addComponent(SameAsBillCheckBox))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CustOrderListBoxLbl)
                .addComponent(CustShipStateComB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(CustOrderListBox)
                .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                        .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustShipStreet1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustShipStreet1Lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustShipStreet2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustShipStreet2Lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustShipCityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustShipCityLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustShipZipText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustShipZipLbl)
                            .addComponent(CustShipStateCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(CustomerInfoPanelLayout.createSequentialGroup()
                        .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustBillFNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustBillFNameLbl)
                            .addComponent(CustShipFNameLbl)
                            .addComponent(CustShipFNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustBillLNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustBillLNameLbl)
                            .addComponent(CustShipLNameLbl)
                            .addComponent(CustShipLNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustBillOrgText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustBillOrgLbl)
                            .addComponent(CustShipOrgLbl)
                            .addComponent(CustShipOrgText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustBillStreet1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustBillStreet1Lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustBillStreet2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustBillStreet2Lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustBillCityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustBillCityLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustBillZipText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustBillZipLbl)))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(CustomerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(CustFindButton)
                .addComponent(CustCreateButton)
                .addComponent(CustCreateButton1)
                .addComponent(ActiveOrderLbl))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(CustCommentLbl)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(CustCommBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(93, Short.MAX_VALUE))
    );

    WSCInterface.addTab("Customer Info", CustomerInfoPanel);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(WSCInterface)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(WSCInterface)
    );

    bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void CustCreateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustCreateButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustCreateButton1ActionPerformed

    private void CustCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustCreateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustCreateButtonActionPerformed

    private void CustFindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustFindButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustFindButtonActionPerformed

    private void CustShipLNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustShipLNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustShipLNameTextActionPerformed

    private void CustShipStreet1TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustShipStreet1TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustShipStreet1TextActionPerformed

    private void CustShipStreet2TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustShipStreet2TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustShipStreet2TextActionPerformed

    private void CustShipZipTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustShipZipTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustShipZipTextActionPerformed

    private void SameAsBillCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SameAsBillCheckBoxActionPerformed
        
    }//GEN-LAST:event_SameAsBillCheckBoxActionPerformed

    private void CustBillZipTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustBillZipTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustBillZipTextActionPerformed

    private void CustBillStreet2TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustBillStreet2TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustBillStreet2TextActionPerformed

    private void CustBillLNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustBillLNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustBillLNameTextActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void OrderCustomerNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderCustomerNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderCustomerNumberTextActionPerformed

    private void OrderPECompleteRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderPECompleteRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderPECompleteRBActionPerformed

    private void OrderCreatedRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderCreatedRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderCreatedRBActionPerformed

    private void OrderDepositTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderDepositTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderDepositTextActionPerformed

    private void LoginPasswordFieldTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPasswordFieldTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginPasswordFieldTextActionPerformed

    private void LoginEMPIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginEMPIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginEMPIDFieldActionPerformed

    private void LoginSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginSubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginSubmitButtonActionPerformed

    private void CustShipStateComBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustShipStateComBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustShipStateComBActionPerformed

    private void CustShipStateCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustShipStateCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustShipStateCBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActiveOrderLbl;
    private javax.swing.JLabel BillingLbl;
    private javax.swing.JLabel CustBillCityLbl;
    private javax.swing.JTextField CustBillCityText;
    private javax.swing.JLabel CustBillFNameLbl;
    private javax.swing.JTextField CustBillFNameText;
    private javax.swing.JLabel CustBillLNameLbl;
    private javax.swing.JTextField CustBillLNameText;
    private javax.swing.JLabel CustBillOrgLbl;
    private javax.swing.JTextField CustBillOrgText;
    private javax.swing.JLabel CustBillStreet1Lbl;
    private javax.swing.JTextField CustBillStreet1Text;
    private javax.swing.JLabel CustBillStreet2Lbl;
    private javax.swing.JTextField CustBillStreet2Text;
    private javax.swing.JLabel CustBillZipLbl;
    private javax.swing.JTextField CustBillZipText;
    private javax.swing.JScrollPane CustCommBox;
    private javax.swing.JLabel CustCommentLbl;
    private javax.swing.JTextArea CustCommentText;
    private javax.swing.JButton CustCreateButton;
    private javax.swing.JButton CustCreateButton1;
    private javax.swing.JButton CustFindButton;
    private javax.swing.JLabel CustNumberLbl;
    private javax.swing.JTextField CustNumberText;
    private javax.swing.JScrollPane CustOrderListBox;
    private javax.swing.JLabel CustOrderListBoxLbl;
    private javax.swing.JLabel CustShipCityLbl;
    private javax.swing.JTextField CustShipCityText;
    private javax.swing.JLabel CustShipFNameLbl;
    private javax.swing.JTextField CustShipFNameText;
    private javax.swing.JLabel CustShipLNameLbl;
    private javax.swing.JTextField CustShipLNameText;
    private javax.swing.JLabel CustShipOrgLbl;
    private javax.swing.JTextField CustShipOrgText;
    private javax.swing.JComboBox CustShipStateCB;
    private javax.swing.JComboBox CustShipStateComB;
    private javax.swing.JLabel CustShipStreet1Lbl;
    private javax.swing.JTextField CustShipStreet1Text;
    private javax.swing.JLabel CustShipStreet2Lbl;
    private javax.swing.JTextField CustShipStreet2Text;
    private javax.swing.JLabel CustShipZipLbl;
    private javax.swing.JTextField CustShipZipText;
    private javax.swing.JPanel CustomerInfoPanel;
    private javax.swing.JTextField LoginEMPIDField;
    private javax.swing.JLabel LoginEMPIDLabel;
    private javax.swing.JLabel LoginPASSLabel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPasswordField LoginPasswordFieldText;
    private javax.swing.JButton LoginSubmitButton;
    private javax.swing.JPanel MediaInventoryPanel;
    private javax.swing.JRadioButton OrderAccountPayRB;
    private javax.swing.JRadioButton OrderClosedRB;
    private javax.swing.JLabel OrderContentLbl;
    private javax.swing.JTextField OrderContentText;
    private javax.swing.JRadioButton OrderCreatedRB;
    private javax.swing.JLabel OrderCustNumberLbl;
    private javax.swing.JTextField OrderCustomerNumberText;
    private javax.swing.JRadioButton OrderDeliverPayRB;
    private javax.swing.JLabel OrderDepositLbl;
    private javax.swing.JTextField OrderDepositText;
    private javax.swing.JLabel OrderDetailsLbl;
    private javax.swing.JScrollPane OrderDetailsText;
    private javax.swing.ButtonGroup OrderEngMediaBG;
    private javax.swing.JRadioButton OrderHoldForPayRB;
    private javax.swing.JPanel OrderInfoPanel;
    private javax.swing.JLabel OrderJobTypeLbl;
    private javax.swing.JRadioButton OrderMDeliveredRB;
    private javax.swing.JRadioButton OrderMEnRouteRB;
    private javax.swing.JRadioButton OrderMNotRequested;
    private javax.swing.JRadioButton OrderMNotVerified;
    private javax.swing.JRadioButton OrderMOnOrderRB;
    private javax.swing.JRadioButton OrderMSoldRB;
    private javax.swing.JLabel OrderMediaCatNumLbl;
    private javax.swing.JTextField OrderMediaCatNumText;
    private javax.swing.JRadioButton OrderMediaHoldRB;
    private javax.swing.ButtonGroup OrderMediaStatusBG;
    private javax.swing.JLabel OrderMediaStatusRBLbl;
    private javax.swing.JLabel OrderNumberLbl;
    private javax.swing.JTextField OrderNumberText;
    private javax.swing.JRadioButton OrderPECompleteRB;
    private javax.swing.ButtonGroup OrderPayTypeBG;
    private javax.swing.JRadioButton OrderQAFailedRB;
    private javax.swing.JRadioButton OrderQAPassedRB;
    private javax.swing.ButtonGroup OrderStatusBG;
    private javax.swing.JLabel OrderStatusRBLbl;
    private javax.swing.JPanel OrderTrackingPanel;
    private javax.swing.ButtonGroup OrderTypeBG;
    private javax.swing.JRadioButton OrderTypeEngrRB;
    private javax.swing.JRadioButton OrderTypePlaqueRB;
    private javax.swing.JRadioButton OrderTypePrintRB;
    private javax.swing.JRadioButton OrderTypeTrophyRB;
    private javax.swing.JRadioButton OrderVerifiedRB;
    private javax.swing.JRadioButton OrderWorkingRB;
    private javax.swing.JPanel QAPanel;
    private javax.swing.JCheckBox SameAsBillCheckBox;
    private javax.swing.JLabel ShippLbl;
    private javax.swing.JTabbedPane WSCInterface;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
